# Parses the logfmt output written by ballerina/log and ballerinax/metrics.logs
# (see each package's Config.toml -> [ballerina.log] format = "logfmt").
[PARSER]
    Name        bal_logfmt_parser
    Format      logfmt
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   On
