[package]
org = "wso2"
name = "sales_order_store"
version = "0.1.0"
distribution = "2201.13.4"
title = "Sales Order Store"

[build-options]
sticky = true
remoteManagement = true
observabilityIncluded = true
